services:
  vakhtangov-bot:
    image: lobanovsky/vakhtangov-bot:${TAG}
    container_name: vakhtangov-bot
    restart: always
    environment:
      TZ: Europe/Moscow
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      BACKEND_URL: ${BACKEND_URL}
      VAKHTANGOV_API_KEY: ${VAKHTANGOV_API_KEY}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      WEBHOOK_PORT: ${WEBHOOK_PORT:-8081}
    ports:
      - "${WEBHOOK_PORT:-8081}:${WEBHOOK_PORT:-8081}"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
